Repository rems-project/cn, pull requests merged in 2025-04, with the labels that each got.

#35 Delete index term operators
  lib/indexTerms.ml
  lib/pack.ml
Labels: cn, technical debt

#41 Fix integer literals in Fulminate
  lib/fulminate/cn_to_ail.ml
  lib/fulminate/executable_spec.ml
  tests/cn/max_min_consts.c
Labels: bug, CN-exec

#40 Add README details for opam installation
  README.md
Labels: documentation

#43 Ignore unused filters with `lcov`
  lib/testGeneration/buildScript.ml
Labels: CN spec testing

#45 Fix non-null pointer generation
  lib/testGeneration/genOptimize.ml
  runtime/libcn/include/cn-testing/dsl.h
  tests/cn-test-gen/src/tutorial_queue.pass.c
Labels: bug, CN spec testing

#48 Reduce redundant structs for generators
  lib/fulminate/cn_to_ail.ml
  lib/fulminate/cn_to_ail.mli
  lib/testGeneration/genCodeGen.ml
  runtime/libcn/include/cn-testing/test.h
Labels: bug, CN spec testing

#57 Don't allow warnings in runtime library
  runtime/libcn/lib/dune
Labels: CI, CN spec testing, CN-exec

#59 Get rid of redundant `Executable_spec` prefixes
  bin/instrument.ml
  bin/seqTest.ml
  bin/test.ml
  lib/bugExplanation/bugExplanation.mli
  lib/bugExplanation/replicators.ml
  lib/bugExplanation/replicators.mli
  lib/bugExplanation/shapeAnalyzers.ml
  lib/bugExplanation/shapeAnalyzers.mli
  lib/fulminate/cn_to_ail.ml
  lib/fulminate/cn_to_ail.mli
  lib/fulminate/extract.ml
  lib/fulminate/extract.mli
  lib/fulminate/fulminate.ml
  lib/fulminate/internal.ml
  lib/fulminate/internal.mli
  lib/fulminate/ownership.ml
  lib/fulminate/ownership.mli
  lib/fulminate/records.ml
  lib/fulminate/utils.ml
  lib/fulminate/utils.mli
  lib/seqTests/seqTests.ml
  lib/testGeneration/genBuiltins.ml
  lib/testGeneration/genCodeGen.ml
  lib/testGeneration/genCompile.ml
  lib/testGeneration/genCompile.mli
  lib/testGeneration/specTests.ml
  lib/testGeneration/specTests.mli
  lib/testGeneration/testGeneration.ml
  lib/testGeneration/testGeneration.mli
Labels: CN-exec, technical debt

#64 Clean up Fulminate flags
  bin/instrument.ml
  runtime/libcn/libexec/cn-runtime-single-file.sh
Labels: CN-exec, technical debt

#67 Run instrumented file with `--run` flag
  bin/instrument.ml
  lib/fulminate/fulminate.ml
  runtime/libcn/libexec/cn-runtime-single-file.sh
Labels: enhancement, CN-exec

#69 Unify suffixes for `cn instrument` and `cn test`
  doc/README-FULMINATE.md
  lib/fulminate/fulminate.ml
  lib/seqTests/buildScript.ml
  lib/seqTests/seqTests.ml
  lib/testGeneration/buildScript.ml
  lib/testGeneration/genCodeGen.ml
  lib/testGeneration/genCodeGen.mli
  lib/testGeneration/specTests.ml
  lib/testGeneration/specTests.mli
  lib/testGeneration/testGeneration.ml
  runtime/libcn/libexec/cn-runtime-single-file.sh
  tests/cn-exec-performance-stats.py
Labels: enhancement, CN spec testing, CN-exec

#78 Update instrumentation and testing READMEs
  doc/README-FULMINATE.md
  doc/TESTING.md
Labels: documentation

#87 Fix local `run-cn-test-gen.sh`
  runtime/libcn/include/cn-testing/test.h
Labels: bug

#94 Clean up `make format`
  Makefile
Labels: technical debt

#108 [CN-Exec] Do not inject synthesized terms
  cn.opam
  lib/fulminate/fulminate.ml
  tests/cn/list_literal_type.error.c.verify
  tests/cn/tree16/as_auto_mutual_dt/tree16.error.c.verify
Labels: CN-exec

#112 Run Clang in testing CI
  .github/workflows/spec-testing.yml
Labels: CI
